#!/bin/bash

#Start centos docker
#docker run -w /data -it --mount type=bind,src="$(pwd)",dst=/data --mount type=bind,src="$(cd ~/; pwd)",dst=/opt/home -p 0.0.0.0:80:8080/tcp centos /bin/bash -c "\
#docker run -w /data -it --mount type=bind,src="$(pwd)",dst=/data --mount type=bind,src="$(cd ~/; pwd)",dst=/opt/home centos /bin/bash -c "\
#        cp -r /opt/home/.aws /root/ && \
#        cp /opt/home/.vimrc /root/ && \
#        /bin/bash"
#docker run -it --volume "$(pwd)":/data -p 0.0.0.0:80:8080/tcp centos bash

docker run --rm -w /data -it --mount type=bind,src="$(pwd)",dst=/data --mount type=bind,src="$(cd ~/; pwd)",dst=/opt/home centos /bin/bash -c "\
        yum install epel-release -y && \
        yum install groff vim python-pip -y && \
        cp -r /opt/home/.aws /root/ && \
        cp /opt/home/.vimrc /root/ && \
        /bin/bash"
