#!/bin/bash

#docker run --rm -w /data -it --mount type=bind,src="$(pwd)",dst=/data --mount type=bind,src="$(cd ~/; pwd)",dst=/opt/home centos /bin/bash -c "\
#        yum install epel-release -y && \
#        yum install groff vim python-pip -y && \
#        cp -r /opt/home/.aws /root/ && \
#        cp /opt/home/.vimrc /root/ && \
#        /bin/bash"
sudo docker run --rm -w /data -p 443:443 -p 80:80 -it --mount type=bind,src="$(pwd)",dst=/data --mount type=bind,src="$(cd ~/; pwd)",dst=/opt/home fedora:latest /bin/bash -c "\
        yum install groff iputils vim python-pip -y && \
        /bin/bash"
